### ISSUE TITLE
(Question)SBB API Rate Limit

### ISSUE THREAD

**Issue by PhilipGossmann** [OpendataCH/Transport#139]
We are getting an error "Rate limit of 300 requests per minute exceeded" when using SBB API http://transport.opendata.ch/v1/

This seems very odd to us since we should be the only one hitting the API and app it self is issuing 3 requests in order to get connection results. This happens once in a while, don't see any regular pattern.

The error occurs on different endpoints, for example http://transport.opendata.ch/v1/connections?from=Geneve&to=Zurich, also for http://transport.opendata.ch/v1/locations?query=Geneve

We experiencing the same thing on our local development machine and on test server which is setup on heroku.

Can somebody help us?

**Comment by fabian** [comment]
Due to a misconfiguration the rate limiting was not working properly yesterday, but it has been fixed yesterday around 16.00.

Can you confirm you are still seeing the HTTP error 429 - "Rate limit of 300 requests per minute exceeded" today?

Please note that you might get HTTP error 500 or 503 at the moment as fahrplan.sbb.ch is not working properly. Check https://status.transport.opendata.ch for the latest updates.

**Comment by PhilipGossmann** [comment]
Thanks a lot for the quick answer!!!

**Comment by fabian** [comment]
The problem at SBB has now been fixed, everything should be back to normal.
